services:
    Cethyworks\GoogleMapDisplayBundle\Command\Handler\GoogleMapDisplayCommandHandler:
        arguments:
            - "@Cethyworks\\ContentInjectorBundle\\EventSubscriber\\ContentInjectorSubscriber"
            - "@twig"
            - "%cethyworks.google_map_display.google_api_key%"
