services:
    # Wrapper
    Cethyworks\GoogleMapDisplayBundle\Command\Wrapper\GoogleMapDisplayCommandWrapper:
        arguments:
            - "@twig"
            - "%cethyworks.google_map_display.google_api_key%"
